base:
  # 存在する特徴量だとしても上書きするか
  overwrite: true
  seed: 1234
  n_folds: 2
  # optunaを使うかどうか
  optuna: true
  num_boost_round: 1500

# LightGBMのパラメータ
parameters:
  objective: "multiclass"
  num_class: 9
  max_depth: 8
  learning_rate: .02
  metric: "multi_logloss"
  num_leaves: 31
  verbose_eval: 500

# trainingに使用する特徴量
features: [
  "base_data",
  "pca",
]
