base:
  # 存在する特徴量だとしても上書きするか
  overwrite: true
  seed: 1234
  n_folds: 4
  # optunaを使うかどうか
  optuna: true
  num_boost_round: 1500

defaults:
  - model: lightgbm


# LightGBMのパラメータ
parameters:
  objective: "multiclass"
  num_class: 9
  max_depth: 8
  learning_rate: .01
  feature_fraction: 0.8
  bagging_freq: 1
  bagging_fraction: 0.8
  metric: "multi_logloss"
  num_leaves: 32
  early_stopping_rounds: 50
  #verbose: -1
  verbose_eval: 500
  force_row_wise: true

# trainingに使用する特徴量
features: [
  "base_data",
  "pca",
]
